[package]
name = "seccamp-2020-os"
version = "0.1.0"
authors = ["sksat <sksat@sksat.net>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
